parserOptions:
    sourceType: "module"
    project: "./tsconfig.json"
extends: [ "janus/ts", "janus/security"]
rules: {
    "@typescript-eslint/ban-types": ["error",
    {
        "types": {
            "Function": false,
        },
        "extendDefaults": true
    }
]
}
ignorePatterns: [ "built/**/*", "*.eslintrc.*" ]
